package Modelos;

public enum Evento {
    NUEVA_RONDA,
    NUEVO_TURNO,
    JUGADOR_TOMO_CARTA_MAZO,
    JUGADOR_TOMO_CARTA_POZO,
    JUGADOR_SE_BAJO,
    JUGADOR_NO_PUDO_BAJARSE,
    JUGADOR_DEJO_CARTA,
    JUGADOR_BAJO_CARTA,
    JUGADOR_NO_PUDO_BAJAR_CARTA,
    TERMINO_RONDA,
    TERMINO_JUEGO,
    NUEVO_JUGADOR_AGREGADO,
    INICIAR_JUEGO,
    FALTAN_JUGADORES
}
